// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mspsecksuupsdrftrllg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcHNlY2tzdXVwc2RyZnRybGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1Mzk1NDksImV4cCI6MjA4NzExNTU0OX0.0E3zT4jdj0soUxd93lCFWuyt7jJqvNMnq8pFQYL4-lo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);